name: Build, Test, and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  issues:
    types:
      - opened


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with: 
          python-version: '3.8'
      - name: Install pip
        run: pip install --upgrade pip
      
      - name: Install Flake8
        run: pip install flake8
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run unit tests
        run: python3 myunittest.py

      - name: Deploy
        run: echo "deploying..........." 
